import React from 'react';

const PayslipGenerator = ({ employee, selectedMonth }) => {
  return (
    <div className="space-y-4">
      <h2 className="text-xl font-bold text-slate-900">Payslip for {employee.employee_name}</h2>
      <p className="text-slate-500">Month: {selectedMonth}</p>
      <div className="grid grid-cols-1 gap-2">
        <p><strong>Employee ID:</strong> {employee.employee_id}</p>
        <p><strong>Department:</strong> {employee.department}</p>
        <p><strong>Gross Salary:</strong> ₹{employee.gross_salary.toLocaleString('en-IN')}</p>
        <p><strong>PF Deduction:</strong> ₹{(employee.pf_deduction || 0).toLocaleString('en-IN')}</p>
        <p><strong>ESIC Deduction:</strong> ₹{(employee.esic_deduction || 0).toLocaleString('en-IN')}</p>
        <p><strong>Tax Deduction:</strong> ₹{(employee.tax_deduction || 0).toLocaleString('en-IN')}</p>
        <p><strong>Net Salary:</strong> ₹{employee.net_salary.toLocaleString('en-IN')}</p>
        <p><strong>Status:</strong> {employee.status}</p>
        <p><strong>Payment Method:</strong> {employee.payment_method}</p>
        <p><strong>Payment Date:</strong> {employee.payment_date}</p>
        <p><strong>Generated by:</strong> {employee.created_by}</p>
      </div>
    </div>
  );
};

export default PayslipGenerator; 